import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/layout/Nav";
import CategoriesList from "@/components/CategoriesList";
import AuthProvider from "@/context/AuthProvider";
import NewArticleLink from "@/components/NewArticleLink";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Nav />
          <div className="mx-72 my-14 grid grid-cols-7 gap-16">
            <div className="col-span-5">{children}</div>
            <div className="col-span-2 flex flex-col gap-4">
              <NewArticleLink />
              <CategoriesList />
            </div>
          </div>
        </AuthProvider>
        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          progressStyle={{ backgroundColor: "#7564d8" }}
        />
      </body>
    </html>
  );
}
